google_analytics: UA-9732793-1

description: >
  My name is Josh and I write software. I also collect movies, toys, and play video games.

author:
  name: Joshua May

show_excerpts: true
minima:
  social_links:
    twitter: twotymz
    github: twotymz
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
